# Version worked on local machine - commands worked!

FROM python:3.10

WORKDIR /app

RUN git clone https://github.com/tttianhao/CLEAN

WORKDIR /app/CLEAN

RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html

RUN git clone https://github.com/facebookresearch/esm.git

RUN mkdir data/esm_data
RUN mkdir data/pretrained

# Download pretrained weights
RUN pip install gdown
RUN gdown --id 1zrEU-HPNV3wp7wLAx4KnuiVyD794Oboj
RUN apt-get update && apt-get install -y unzip
RUN unzip CLEAN_pretrained.zip -d data/pretrained

# 
RUN python build.py install

