# Not working locally and not working on VM
FROM continuumio/miniconda3:latest

RUN conda update -n base -c defaults conda

# Create a new conda environment and activate it
RUN conda create --name myenv

# Set the new environment as the default
RUN echo "conda activate myenv" >> ~/.bashrc
ENV PATH /opt/conda/envs/myenv/bin:$PATH

# Install packages in the new environment
RUN conda install pytorch cpuonly -c pytorch

# Set the working directory
WORKDIR /app

# RUN git clone https://github.com/tttianhao/CLEAN
COPY CLEAN /app/

RUN apt-get update && apt-get install -y gcc && apt-get install -y g++
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# RUN pip install torch torchvision torchaudio -f https://download.pytorch.org/whl/cu111/torch_stable.html

# RUN git clone https://github.com/facebookresearch/esm.git

# RUN mkdir data/esm_data
# RUN mkdir data/pretrained

# Download pretrained weights
# RUN pip install gdown
# RUN gdown --id 1zrEU-HPNV3wp7wLAx4KnuiVyD794Oboj
# RUN apt-get update && apt-get install -y unzip
# RUN unzip CLEAN_pretrained.zip -d data/pretrained

# 
RUN python build.py install
